-- Input fixtures are generated by test_capture.py from synthetic bytes only.
CowboyBingusModLoader={api=1,version=16}
local M=assert(dofile(assert(arg[1])))
local cases=assert(dofile(assert(arg[2])))
for _,case in ipairs(cases) do
    local ok,result=pcall(M.inspect_snapshot,case.capture)
    assert(ok==case.accept, case.name..': '..tostring(result))
    if ok then
        assert(result.matching_ready==false and result.atomic_snapshot==false)
        -- Emit a bounded projection for Python to compare with its own decoder.
        for _,op in ipairs(result.operations) do
            local types,seeds={},{}
            for _,mission in ipairs(op.missions) do
                types[#types+1]=mission.native_type
                seeds[#seeds+1]=mission.seed
            end
            print(case.name..'|'..op.row..'|'..op.difficulty..'|'..table.concat(types,',')..'|'..table.concat(seeds,','))
        end
    end
end
